site_name: Musket ML
theme:
  name: null
  custom_dir: readthedocs_mod
  navigation_depth: 4
  highlightjs: true
  hljs_languages:
    - yaml
    - Python
#theme: readthedocs
#theme:
#  name: null
#  custom_dir: theme
#  static_templates:
#    - 404.html
#  include_search_page: true
#  search_index_only: false
#  highlightjs: true
#  hljs_languages: []
#  include_homepage_in_sidebar: true
#  prev_next_buttons_location: bottom
#  navigation_depth: 4
#  titles_only: false
#  sticky_navigation: true
#  collapse_navigation: true
nav:
- Home: 'index.md'
- Generic:
    - 'User guide': 'generic/index.md'
    - 'Reference': 'generic/reference.md'
- Segmentation:
    - 'Getting started': 'segmentation/getting_started.md'
    - 'User guide': 'segmentation/index.md'
    - 'Reference': 'segmentation/reference.md'
- Classification:
    - 'User guide': 'classification/index.md'
    - 'Reference': 'classification/reference.md'
- Text:
    - 'About': 'text/index.md'
- Musket IDE:
    - 'Getting started': 'ide/getting_started.md'
#- Instance Segmentation:
#    - 'User guide': 'instance_segmentation/index.md'
#    - 'Reference': 'instance_segmentation/reference.md'